### ISSUE TITLE
Keeping extra sheets

### ISSUE THREAD

**Issue by darroyotelcomunity** [mindspank/architeqt#10]
Hello, first of all I want to thank you for your great job.

I have a blueprint app with 5 sheets and a "use blueprint" app with 6 sheets. I would like synchronize copy the blueprint 5 sheets, but not removing that extra sheet of the child app.

Is this possible?

Best regards,
David.

**Comment by mindspank** [comment]
Hey,
Yes, whatever assets that has been created in a "child app" is not touched by the module.
