### ISSUE TITLE
Error - "Something went wrong using sync."

### ISSUE THREAD

**Issue by rodjager** [mindspank/architeqt#9]
Hi,

I have installed architeqt under Qlik Sense 2.2.3 and am encountering an error when I attempt to sync from a Blueprint or from a child.

The error message is displayed in a popup that has the title "Failure" and the message "Something went wrong using sync.  Please review server logs."

Attached is the architeqt.log file.  I had a quick look and couldn't see anything obvious but I am not sure what I should be looking for/at.

Everything else appears to be working as expected.

Let me know if I can provide any additional information.

Rod
[architeqt.txt](https://github.com/mindspank/architeqt/files/336709/architeqt.txt)

**Comment by mindspank** [comment]
Checking the log reveals a Operation Aborted error which seems strange, might be a race condition somewhere. Would it be possible to get a copy of the parent application to do more deep testing? If so you can email me at akl at qlik dot com
